const EXT_MAP: Record<string, string> = {
  ts: 'typescript',
  tsx: 'tsx',
  js: 'javascript',
  jsx: 'jsx',
  rs: 'rust',
  py: 'python',
  rb: 'ruby',
  go: 'go',
  java: 'java',
  kt: 'kotlin',
  c: 'c',
  h: 'c',
  cpp: 'cpp',
  cc: 'cpp',
  cxx: 'cpp',
  hpp: 'cpp',
  cs: 'csharp',
  swift: 'swift',
  zig: 'zig',
  lua: 'lua',
  php: 'php',
  pl: 'perl',
  r: 'r',
  scala: 'scala',
  ex: 'elixir',
  exs: 'elixir',
  erl: 'erlang',
  hs: 'haskell',
  ml: 'ocaml',
  mli: 'ocaml',
  clj: 'clojure',
  lisp: 'lisp',
  sql: 'sql',
  sh: 'bash',
  bash: 'bash',
  zsh: 'bash',
  fish: 'bash',
  ps1: 'powershell',
  json: 'json',
  yaml: 'yaml',
  yml: 'yaml',
  toml: 'toml',
  xml: 'markup',
  html: 'markup',
  htm: 'markup',
  svg: 'markup',
  css: 'css',
  scss: 'scss',
  sass: 'sass',
  less: 'less',
  md: 'markdown',
  mdx: 'markdown',
  tex: 'latex',
  nix: 'nix',
  diff: 'diff',
  patch: 'diff',
  ini: 'ini',
  cfg: 'ini',
  graphql: 'graphql',
  gql: 'graphql',
  proto: 'protobuf',
  dockerfile: 'docker',
  tf: 'hcl',
  hcl: 'hcl',
  vim: 'vim',
  el: 'lisp',
  rkt: 'scheme',
  dart: 'dart',
  v: 'v',
  asm: 'nasm',
  s: 'nasm',
  wasm: 'wasm',
};

const NAME_MAP: Record<string, string> = {
  Makefile: 'makefile',
  makefile: 'makefile',
  GNUmakefile: 'makefile',
  Dockerfile: 'docker',
  Containerfile: 'docker',
  Justfile: 'makefile',
  justfile: 'makefile',
  Gemfile: 'ruby',
  Rakefile: 'ruby',
  'CMakeLists.txt': 'cmake',
  '.gitignore': 'git',
  '.gitmodules': 'git',
  '.gitattributes': 'git',
  '.bashrc': 'bash',
  '.bash_profile': 'bash',
  '.zshrc': 'bash',
  '.zshenv': 'bash',
  '.profile': 'bash',
  '.env': 'bash',
  '.env.local': 'bash',
  '.env.example': 'bash',
  'tsconfig.json': 'json',
  'package.json': 'json',
  'Cargo.toml': 'toml',
  'Cargo.lock': 'toml',
  'flake.nix': 'nix',
  'flake.lock': 'json',
  'default.nix': 'nix',
  'shell.nix': 'nix',
};

export function getLanguage(filename: string): string {
  if (NAME_MAP[filename]) return NAME_MAP[filename];
  const ext = filename.split('.').pop()?.toLowerCase() ?? '';
  return EXT_MAP[ext] ?? 'text';
}
